###############################################################################
# Copyright (c) 2016, 2019 itemis AG and others.
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Alexander Nyßen (itemis AG) - initial API and implementation
#     Zoey Prigge (itemis AG) - add manual trusty distribution
###############################################################################

sudo: false

language: java

jdk: 
 - openjdk11

dist: trusty

cache:
  directories:
  - $HOME/.m2

before_script:
  - "wget https://download2.gluonhq.com/openjfx/11.0.2/openjfx-11.0.2_linux-x64_bin-sdk.zip -O /tmp/openjfx11.zip"
  - "unzip /tmp/openjfx11.zip -d /tmp"
  - "export JAVAFX_HOME=/tmp/javafx-sdk-11.0.2"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 

script:
- cd org.eclipse.gef.releng
# skip wikidoc generation, which does not affect build result, but generate javadoc and ensure test failures are respected.
- travis_wait 30 mvn clean verify -Dmaven.test.failure.ignore=false -Dwikidoc.skip=true -P2019-03.target
